require("jvrviegas.plugins.theme")
require("jvrviegas.plugins.nvim-tree")
require("jvrviegas.plugins.telescope")
require("jvrviegas.plugins.cmp")
require("jvrviegas.plugins.lsp")
require("jvrviegas.plugins.autopairs")
require("jvrviegas.plugins.lualine")
require("jvrviegas.plugins.treesitter")
require("jvrviegas.plugins.gitsigns")
require("jvrviegas.plugins.comment")
require("jvrviegas.plugins.trouble")
require("jvrviegas.plugins.toggleterm")

vim.cmd([[let g:blamer_enabled = 1]])
vim.cmd([[let g:blamer_delay = 500]])
